# Generated by Django 5.0.4 on 2024-05-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("content", models.CharField(max_length=1000, verbose_name="Заметка")),
            ],
            options={
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметки",
            },
        ),
    ]
